# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Set Global Git Config
        run: |
          git config --global user.email "mcodesido@baufest.com"
          git config --global user.name "Mateo Codesido"

      - name: Bump Version
        run: npm version ${{ github.event.release.tag_name }}
        working-directory: projects/input-with-suggestions-lib

      - name: Install Dependencies
        run: npm ci
        working-directory: projects/input-with-suggestions-lib

      - name: Build
        run: npm run build
        working-directory: projects/input-with-suggestions-lib

      - name: Publish Package
        run: npm publish
        working-directory: projects/input-with-suggestions-lib
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
