# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  workflow_dispatch:
    inputs:
      example_input:
        description: 'An example input'
        required: false
        default: 'default_value'
  release:
    types: [created]
  

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.20.0'  # Change back to Node.js 16.x which is more compatible with older packages
          registry-url: 'https://registry.npmjs.org/'
          
      - name: Setup Python 2
        uses: actions/setup-python@v4
        with:
          python-version: '2.7'  # Install Python 2.7 for node-sass
          
      - name: Update package.json for compatible Angular version
        run: |
          node -e '
            const fs = require("fs");
            const pkg = JSON.parse(fs.readFileSync("package.json", "utf8"));
            
            // Keep Angular versions consistent with what's in package.json (Angular 7)
            // Do not upgrade to Angular 14 which creates dependency conflicts
            
            fs.writeFileSync("package.json", JSON.stringify(pkg, null, 2));
          '
      
      - name: Generate new package-lock.json
        run: npm install --package-lock-only --legacy-peer-deps
      
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      
      - name: Install Angular CLI globally and build
        run: |
          npm install -g @angular/cli@14.2.0
          
          # Create necessary tsconfig files
          echo '{
            "compileOnSave": false,
            "compilerOptions": {
              "baseUrl": "./",
              "outDir": "./dist/out-tsc",
              "sourceMap": true,
              "declaration": false,
              "downlevelIteration": true,
              "experimentalDecorators": true,
              "module": "es2020",
              "moduleResolution": "node",
              "importHelpers": true,
              "target": "es2015",
              "typeRoots": [
                "node_modules/@types"
              ],
              "lib": [
                "es2018",
                "dom"
              ],
              "skipLibCheck": true
            },
            "angularCompilerOptions": {
              "enableI18nLegacyMessageIdFormat": false,
              "strictInjectionParameters": true,
              "strictInputAccessModifiers": true,
              "strictTemplates": true
            }
          }' > tsconfig.json
          
          echo '{
            "extends": "./tsconfig.json",
            "compilerOptions": {
              "outDir": "./out-tsc/lib",
              "declaration": true,
              "declarationMap": true,
              "inlineSources": true,
              "types": []
            },
            "exclude": [
              "src/test.ts",
              "**/*.spec.ts"
            ]
          }' > tsconfig.lib.json
          
          echo '{
            "extends": "./tsconfig.lib.json",
            "compilerOptions": {
              "declarationMap": false
            },
            "angularCompilerOptions": {
              "compilationMode": "partial"
            }
          }' > tsconfig.lib.prod.json
          
          # Create angular.json if missing
          echo '{
            "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
            "version": 1,
            "newProjectRoot": "projects",
            "projects": {
              "input-with-suggestions-lib": {
                "projectType": "library",
                "root": ".",
                "sourceRoot": "lib",
                "prefix": "lib",
                "architect": {
                  "build": {
                    "builder": "@angular-devkit/build-angular:ng-packagr",
                    "options": {
                      "project": "ng-package.json"
                    },
                    "configurations": {
                      "production": {
                        "tsConfig": "tsconfig.lib.prod.json"
                      },
                      "development": {
                        "tsConfig": "tsconfig.lib.json"
                      }
                    },
                    "defaultConfiguration": "production"
                  }
                }
              }
            }
          }' > angular.json
          
          # Now run the build
          npx ng build input-with-suggestions-lib

      - name: Set Global Git Config
        run: |
          git config --global user.email "mcodesido@baufest.com"
          git config --global user.name "Mateo Codesido"
          
      - name: Clean install directory
        run: rm -rf node_modules package-lock.json
        
      - name: Build library directly
        run: |
          # Examine file structure
          echo "Current directory structure:"
          ls -la
          
          # Check if ng-package.json exists and display its contents
          if [ -f "ng-package.json" ]; then
            echo "Contents of ng-package.json:"
            cat ng-package.json
          fi
          
          # Install dependencies with specific flags for compatibility
          npm install --legacy-peer-deps
          
          # Use ng-packagr directly with the existing configuration
          echo "Building with ng-packagr..."
          npx ng-packagr -p ng-package.json
          
      - name: Publish Package
        run: |
          # Check if the dist directory contains the package files
          echo "Contents of dist directory:"
          ls -la dist
          
          # Navigate to the dist directory and publish from there
          cd dist/input-with-suggestions-lib
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
