# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  workflow_dispatch:
    inputs:
      example_input:
        description: 'An example input'
        required: false
        default: 'default_value'
  release:
    types: [created]
  

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
          
      - name: Set Global Git Config
        run: |
          git config --global user.email "mcodesido@baufest.com"
          git config --global user.name "Mateo Codesido"
      
      - name: Install Dependencies
        run: |
          # Force npm to use legacy peer deps to handle TypeScript version conflicts
          npm config set legacy-peer-deps true
          
          # Skip node-sass during installation
          export SKIP_SASS_BINARY_DOWNLOAD_FOR_CI=true
          export SASS_BINARY_SITE=https://github.com/sass/node-sass/releases/download
          
          # Install dependencies with force flag to resolve conflicts
          npm install --legacy-peer-deps --force
          
          # Remove node-sass to prevent Python dependency issues
          npm rm node-sass --no-save
          
          # Install missing dependencies if any
          npm i --package-lock=false --legacy-peer-deps --force

      - name: Build
        run: npm run build

      - name: Publish Package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
