# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  workflow_dispatch:
    inputs:
      example_input:
        description: 'An example input'
        required: false
        default: 'default_value'
  release:
    types: [created]
  

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.20.0'  # Using a stable Node.js 16.x version
          registry-url: 'https://registry.npmjs.org/'
          
      - name: Update package.json for compatible Angular version
        run: |
          node -e '
            const fs = require("fs");
            const pkg = JSON.parse(fs.readFileSync("package.json", "utf8"));
            
            // Update all devDependencies
            pkg.devDependencies["@angular/cli"] = "14.2.0";
            pkg.devDependencies["@angular/compiler"] = "14.2.0";
            pkg.devDependencies["@angular/compiler-cli"] = "14.2.0";
            pkg.devDependencies["@angular/core"] = "14.2.0";
            pkg.devDependencies["@angular/common"] = "14.2.0";
            pkg.devDependencies["@angular/platform-browser"] = "14.2.0";
            pkg.devDependencies["@angular/platform-browser-dynamic"] = "14.2.0";
            pkg.devDependencies["@angular/router"] = "14.2.0";
            pkg.devDependencies["@angular/forms"] = "14.2.0";
            pkg.devDependencies["@angular-devkit/build-angular"] = "14.2.0";
            pkg.devDependencies["ng-packagr"] = "14.2.0";
            pkg.devDependencies["typescript"] = "~4.6.4";
            
            // Update peerDependencies
            pkg.peerDependencies["@angular/core"] = "^14.0.0";
            pkg.peerDependencies["@angular/common"] = "^14.0.0";
            pkg.peerDependencies["@angular/forms"] = "^14.0.0";
            
            fs.writeFileSync("package.json", JSON.stringify(pkg, null, 2));
          '
      
      - name: Generate new package-lock.json
        run: npm install --package-lock-only --legacy-peer-deps
      
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      
      - name: Install Angular CLI globally and build
        run: |
          npm install -g @angular/cli@14.2.0
          npx ng build input-with-suggestions-lib

      - name: Set Global Git Config
        run: |
          git config --global user.email "mcodesido@baufest.com"
          git config --global user.name "Mateo Codesido"
          
      - name: Clean install directory
        run: rm -rf node_modules package-lock.json
        
      - name: Build library directly
        run: |
          # Create necessary tsconfig files if they don't exist
          if [ ! -f "tsconfig.lib.json" ]; then
            echo '{
              "extends": "./tsconfig.json",
              "compilerOptions": {
                "outDir": "./out-tsc/lib",
                "declaration": true,
                "declarationMap": true,
                "inlineSources": true,
                "types": []
              },
              "exclude": [
                "src/test.ts",
                "**/*.spec.ts"
              ]
            }' > tsconfig.lib.json
          fi

          if [ ! -f "tsconfig.lib.prod.json" ]; then
            echo '{
              "extends": "./tsconfig.lib.json",
              "compilerOptions": {
                "declarationMap": false
              },
              "angularCompilerOptions": {
                "compilationMode": "partial"
              }
            }' > tsconfig.lib.prod.json
          fi

          npx ng-packagr -p ng-package.json

      - name: Build
        run: npm run build

      - name: Publish Package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
