# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  workflow_dispatch:
    inputs:
      example_input:
        description: 'An example input'
        required: false
        default: 'default_value'
  release:
    types: [created]
  

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
          
      - name: Set Global Git Config
        run: |
          git config --global user.email "mcodesido@baufest.com"
          git config --global user.name "Mateo Codesido"
      
      - name: Install Dependencies without node-sass
        run: |
          # Skip node-sass during installation  
          export SKIP_SASS_BINARY_DOWNLOAD_FOR_CI=true
          export SASS_BINARY_SITE=https://github.com/sass/node-sass/releases/download
          
          # Use npm install with --ignore-scripts to prevent node-sass from building
          npm install --ignore-scripts --legacy-peer-deps
          
          # Remove node-sass if it got installed
          npm rm node-sass --no-save
          
          # Install other dependencies that might have been skipped due to --ignore-scripts
          npm rebuild --legacy-peer-deps

      - name: Build
        run: npm run build

      - name: Publish Package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
